version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wishlist_frontend
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost/api/v1}
    restart: unless-stopped
    networks:
      - wishlist_network

networks:
  wishlist_network:
    external: true
    name: wishlist_network
